### ISSUE TITLE
can't parse /usr/include/stdio.h

### ISSUE THREAD

**Issue by lukaszgemborowski** [lukaszgemborowski/pyautobind#8]
```
Traceback (most recent call last):
  File "src/main.py", line 234, in <module>
    main()
  File "src/main.py", line 230, in main
    generate_struct_members(writer, structs)
  File "src/main.py", line 101, in generate_struct_members
    writer.write("(\"%s\", %s)," % (field.displayname, get_field_type(field, structs)), 1)
  File "src/main.py", line 89, in get_field_type
    assert False, "type not found"
AssertionError: type not found
```

**Comment by lukaszgemborowski** [comment]
some standard types was missing in std types dictionary.
